{{- if .Values.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "#RELEASE_NAME#.fullname" . }}
spec:
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "#RELEASE_NAME#.fullname" . }}
  metrics:
  {{- toYaml .Values.autoscaling.metrics | nindent 4 }}
  behavior:
  {{- toYaml .Values.autoscaling.behavior | nindent 4 }}
{{- end }}
