{{- if .Values.oc.route.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "#RELEASE_NAME#.fullname" . }}
spec:
  host: {{ .Values.oc.route.host }}
  path: {{ .Values.context }}
  to:
    kind: Service
    name: {{ include "#RELEASE_NAME#.fullname" . }}
    weight: 100
  port:
    targetPort: http
{{- end }}
